#cloud-config

coreos:
  update:
    reboot-strategy: off
  fleet:
    metadata: slave=yes
    etcd_servers: "http://$REGISTRY_IP:$REGISTRY_PORT"
    agent_ttl: "120s"
  units:
    - name: fleet.service
      command: start
    - name: etcd.service
      command: stop
      mask: yes
    - name: ntpd.service
      command: stop
      mask: yes
    - name: systemd-timesyncd.service
      command: start
      drop-ins:
        - name: 50-enable-in-vm.conf
          content: |
            [Unit]
            ConditionVirtualization=
    - name: sshd.socket
      command: start
      content: |
        [Socket]
        ListenStream=$SSH_PORT
        Accept=yes

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      ClientAliveInterval 180
      UseDNS no

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no
  - path: /etc/systemd/network/01-no-llmnr.conf
    content: |
      [Network]
      LLMNR=false
